// Muscle group definitions with colors — each group has a unique color (used in exercise picker, home card, muscle map, etc.)
export const MUSCLE_GROUPS = {
  chest:     { label: 'Chest',     color: '#7B7BFF', bg: 'rgba(123,123,255,0.1)' },
  back:      { label: 'Back',      color: '#5BF5A0', bg: 'rgba(91,245,160,0.1)' },
  legs:      { label: 'Legs',      color: '#FFAA50', bg: 'rgba(255,170,80,0.1)' },
  shoulders: { label: 'Shoulders', color: '#4ECDC4', bg: 'rgba(78,205,196,0.1)' },
  arms:      { label: 'Arms',      color: '#ff6b6b', bg: 'rgba(255,107,107,0.1)' },
  core:      { label: 'Core',      color: '#C8A0FF', bg: 'rgba(200,160,255,0.1)' },
  cardio:    { label: 'Cardio',    color: '#FFD93D', bg: 'rgba(255,217,61,0.1)' },
  mobility:  { label: 'Mobility',  color: '#F59E0B', bg: 'rgba(245,158,11,0.12)' },
}

// The 16 muscle slugs used for recovery tracking and muscle maps.
// Each exercise can have muscles: { primary: [...slugs], secondary: [...] }.
// If missing, fall back to the 8-group `muscle` field for display and recovery.
export const MUSCLE_SLUGS = [
  'chest', 'front-delts', 'side-delts', 'rear-delts',
  'triceps', 'biceps', 'forearms',
  'back', 'lats', 'traps', 'lower-back',
  'abs', 'obliques',
  'quads', 'hamstrings', 'glutes', 'calves',
]

/** Slug → MUSCLE_GROUPS key for display/color when showing slug tags */
export const SLUG_TO_GROUP = {
  chest: 'chest', 'front-delts': 'shoulders', 'side-delts': 'shoulders', 'rear-delts': 'shoulders',
  triceps: 'arms', biceps: 'arms', forearms: 'arms',
  back: 'back', lats: 'back', traps: 'back', 'lower-back': 'back',
  abs: 'core', obliques: 'core',
  quads: 'legs', hamstrings: 'legs', glutes: 'legs', calves: 'legs',
}

/** Returns unique slugs (primary + secondary) for an exercise from library. Falls back to [muscle] if no muscles. Cardio/mobility with explicit empty arrays return []. */
export function getExerciseSlugs(lib) {
  if (!lib) return []
  const m = lib.muscles
  if (m) {
    const hasSlugs = (m.primary?.length || 0) + (m.secondary?.length || 0) > 0
    if (hasSlugs) {
      const set = new Set([...(m.primary || []), ...(m.secondary || [])])
      return [...set]
    }
    return [] // explicit empty primary/secondary (e.g. cardio, mobility) → no recovery tracking
  }
  if (lib.muscle) return [lib.muscle]
  return []
}

export const EQUIPMENT_TYPES = ['Barbell', 'Dumbbell', 'Cable', 'Machine', 'Bodyweight', 'Kettlebell', 'Band', 'TRX', 'Smith Machine', 'Landmine', 'Other']

// Default exercise library (300 exercises)
export const DEFAULT_EXERCISES = [
  // ===== CHEST (30) =====
  { name: 'Barbell Bench Press',                          muscle: 'chest', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Incline Barbell Bench Press',                  muscle: 'chest', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Decline Barbell Bench Press',                  muscle: 'chest', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Close-Grip Bench Press',                       muscle: 'chest', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['triceps', 'front-delts'] } },
  { name: 'Floor Press',                                  muscle: 'chest', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Dumbbell Bench Press',                         muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Incline Dumbbell Press',                       muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Decline Dumbbell Press',                       muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Dumbbell Flyes',                               muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] } },
  { name: 'Incline Dumbbell Flyes',                       muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] } },
  { name: 'Dumbbell Pullover',                            muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['lats'] } },
  { name: 'Cable Flyes',                                  muscle: 'chest', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] } },
  { name: 'Cable Crossover',                              muscle: 'chest', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] } },
  { name: 'Low Cable Flye',                               muscle: 'chest', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] } },
  { name: 'Machine Chest Press',                          muscle: 'chest', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Incline Machine Press',                        muscle: 'chest', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Pec Deck',                                     muscle: 'chest', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] } },
  { name: 'Smith Machine Bench Press',                    muscle: 'chest', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Smith Machine Incline Press',                  muscle: 'chest', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Chest Dip',                                    muscle: 'chest', equipment: 'Bodyweight',     type: 'bw_reps', muscles: { primary: ['chest', 'triceps'], secondary: ['front-delts'] } },
  { name: 'Push-ups',                                     muscle: 'chest', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Incline Push-ups',                             muscle: 'chest', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Decline Push-ups',                             muscle: 'chest', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Diamond Push-ups',                             muscle: 'chest', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['chest'], secondary: ['triceps', 'front-delts'] } },
  { name: 'Wide Push-ups',                                muscle: 'chest', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Landmine Press',                               muscle: 'chest', equipment: 'Landmine',       type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Single Arm Landmine Press',                    muscle: 'chest', equipment: 'Landmine',       type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Band Chest Press',                             muscle: 'chest', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },
  { name: 'Band Flyes',                                   muscle: 'chest', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] } },
  { name: 'TRX Push-up',                                  muscle: 'chest', equipment: 'TRX',            type: 'reps_only', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] } },

  // ===== BACK (39) =====
  { name: 'Barbell Row',                                  muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Pendlay Row',                                  muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Conventional Deadlift',                        muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'glutes', 'hamstrings'], secondary: ['traps', 'quads'] } },
  { name: 'Sumo Deadlift',                                muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'glutes', 'hamstrings'], secondary: ['traps', 'quads'] } },
  { name: 'Rack Pull',                                    muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'glutes', 'hamstrings'], secondary: ['traps', 'quads'] } },
  { name: 'T-Bar Row',                                    muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Barbell Shrug',                                muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['traps'], secondary: ['back'] } },
  { name: 'Dumbbell Row',                                 muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Dumbbell Shrug',                               muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['traps'], secondary: ['back'] } },
  { name: 'Dumbbell Pullover (Back)',                    muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['lats'], secondary: ['chest'] } },
  { name: 'Incline Dumbbell Row',                         muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Kroc Row',                                     muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Lat Pulldown',                                 muscle: 'back', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] } },
  { name: 'Close-Grip Pulldown',                          muscle: 'back', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] } },
  { name: 'Wide-Grip Pulldown',                           muscle: 'back', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] } },
  { name: 'Straight Arm Pulldown',                        muscle: 'back', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['lats'], secondary: ['triceps'] } },
  { name: 'Seated Cable Row',                             muscle: 'back', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Face Pull',                                    muscle: 'back', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['rear-delts', 'traps'], secondary: ['back'] } },
  { name: 'Single Arm Cable Row',                         muscle: 'back', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Cable Shrug',                                  muscle: 'back', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['traps'], secondary: ['back'] } },
  { name: 'Machine Row',                                  muscle: 'back', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] } },
  { name: 'Chest-Supported Row',                          muscle: 'back', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Reverse Grip Machine Row',                     muscle: 'back', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] } },
  { name: 'Machine Shrug',                                muscle: 'back', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['traps'], secondary: ['back'] } },
  { name: 'Smith Machine Row',                            muscle: 'back', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] } },
  { name: 'Smith Machine Shrug',                          muscle: 'back', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['traps'], secondary: ['back'] } },
  { name: 'Pull-ups',                                     muscle: 'back', equipment: 'Bodyweight',     type: 'bw_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] } },
  { name: 'Chin-ups',                                     muscle: 'back', equipment: 'Bodyweight',     type: 'bw_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] } },
  { name: 'Wide-Grip Pull-ups',                           muscle: 'back', equipment: 'Bodyweight',     type: 'bw_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] } },
  { name: 'Neutral-Grip Pull-ups',                        muscle: 'back', equipment: 'Bodyweight',     type: 'bw_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] } },
  { name: 'Inverted Row',                                 muscle: 'back', equipment: 'Bodyweight',     type: 'bw_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Back Extension',                               muscle: 'back', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['lower-back', 'glutes'], secondary: ['hamstrings'] } },
  { name: 'Landmine Row',                                 muscle: 'back', equipment: 'Landmine',       type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Meadows Row',                                  muscle: 'back', equipment: 'Landmine',       type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'TRX Row',                                      muscle: 'back', equipment: 'TRX',            type: 'reps_only', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Band Pull-Apart',                              muscle: 'back', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['rear-delts', 'traps'], secondary: ['back'] } },
  { name: 'Band Row',                                     muscle: 'back', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Kettlebell Row',                               muscle: 'back', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] } },
  { name: 'Kettlebell Swing',                             muscle: 'back', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['glutes', 'hamstrings'], secondary: ['back', 'traps'] } },

  // ===== LEGS (56) =====
  { name: 'Barbell Back Squat',                           muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Front Squat',                                  muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Zercher Squat',                                muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Pause Squat',                                  muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Box Squat',                                    muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Romanian Deadlift',                            muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },
  { name: 'Stiff-Leg Deadlift',                           muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },
  { name: 'Good Morning',                                 muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },
  { name: 'Barbell Lunge',                                muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Barbell Hip Thrust',                           muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] } },
  { name: 'Barbell Calf Raise',                           muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['calves'], secondary: [] } },
  { name: 'Dumbbell Squat',                               muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Goblet Squat',                                 muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Dumbbell Romanian Deadlift',                   muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },
  { name: 'Dumbbell Lunge',                               muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Walking Lunge',                                muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Bulgarian Split Squat',                        muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Dumbbell Step-up',                             muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Dumbbell Calf Raise',                         muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['calves'], secondary: [] } },
  { name: 'Dumbbell Hip Thrust',                          muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] } },
  { name: 'Cable Pull-Through',                           muscle: 'legs', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['glutes', 'hamstrings'], secondary: ['lower-back'] } },
  { name: 'Cable Kickback',                               muscle: 'legs', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] } },
  { name: 'Cable Hip Adduction',                         muscle: 'legs', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] } },
  { name: 'Cable Hip Abduction',                         muscle: 'legs', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] } },
  { name: 'Leg Press',                                    muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Hack Squat',                                   muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Leg Extension',                                muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['quads'], secondary: [] } },
  { name: 'Seated Leg Curl',                              muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },
  { name: 'Lying Leg Curl',                               muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },
  { name: 'Standing Leg Curl',                            muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },
  { name: 'Hip Adductor Machine',                         muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] } },
  { name: 'Hip Abductor Machine',                         muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] } },
  { name: 'Glute Drive Machine',                          muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] } },
  { name: 'Seated Calf Raise',                            muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['calves'], secondary: [] } },
  { name: 'Standing Calf Raise',                          muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['calves'], secondary: [] } },
  { name: 'Pendulum Squat',                               muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Belt Squat',                                   muscle: 'legs', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Smith Machine Squat',                          muscle: 'legs', equipment: 'Smith Machine',  type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Smith Machine Romanian Deadlift',              muscle: 'legs', equipment: 'Smith Machine',  type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },
  { name: 'Smith Machine Lunge',                          muscle: 'legs', equipment: 'Smith Machine',  type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Smith Machine Hip Thrust',                     muscle: 'legs', equipment: 'Smith Machine',  type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] } },
  { name: 'Smith Machine Calf Raise',                     muscle: 'legs', equipment: 'Smith Machine',  type: 'weight_reps', muscles: { primary: ['calves'], secondary: [] } },
  { name: 'Bodyweight Squat',                             muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Pistol Squat',                                 muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Jump Squat',                                   muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Bodyweight Lunge',                             muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Glute Bridge',                                 muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['glutes'], secondary: ['hamstrings'] } },
  { name: 'Nordic Hamstring Curl',                        muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },
  { name: 'Wall Sit',                                     muscle: 'legs', equipment: 'Bodyweight',     type: 'time_only', muscles: { primary: ['quads'], secondary: ['glutes'] } },
  { name: 'Kettlebell Goblet Squat',                     muscle: 'legs', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Kettlebell Deadlift',                         muscle: 'legs', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Kettlebell Lunge',                             muscle: 'legs', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Band Squat',                                   muscle: 'legs', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Band Leg Curl',                                muscle: 'legs', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },
  { name: 'Landmine Squat',                               muscle: 'legs', equipment: 'Landmine',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] } },
  { name: 'Landmine Romanian Deadlift',                  muscle: 'legs', equipment: 'Landmine',       type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] } },

  // ===== SHOULDERS (35) =====
  { name: 'Barbell Overhead Press',                       muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Push Press',                                   muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Behind-the-Neck Press',                        muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Barbell Upright Row',                          muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['side-delts', 'traps'], secondary: ['front-delts'] } },
  { name: 'Barbell Front Raise',                          muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['front-delts'], secondary: ['side-delts'] } },
  { name: 'Bradford Press',                               muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Dumbbell Shoulder Press',                     muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Arnold Press',                                 muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps'] } },
  { name: 'Lateral Raise',                                muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] } },
  { name: 'Front Raise',                                  muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['front-delts'], secondary: ['side-delts'] } },
  { name: 'Dumbbell Upright Row',                         muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['side-delts', 'traps'], secondary: ['front-delts'] } },
  { name: 'Reverse Flye',                                 muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] } },
  { name: 'Dumbbell Shrug (Shoulders)',                   muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['traps'], secondary: [] } },
  { name: 'Lu Raise',                                     muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] } },
  { name: 'Cable Lateral Raise',                          muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] } },
  { name: 'Cable Front Raise',                            muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['front-delts'], secondary: ['side-delts'] } },
  { name: 'Cable Reverse Flye',                           muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] } },
  { name: 'Cable Upright Row',                            muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['side-delts', 'traps'], secondary: ['front-delts'] } },
  { name: 'Cable Face Pull',                              muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] } },
  { name: 'Cable Shoulder Press',                        muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Machine Shoulder Press',                      muscle: 'shoulders', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Machine Lateral Raise',                        muscle: 'shoulders', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] } },
  { name: 'Reverse Pec Deck',                             muscle: 'shoulders', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] } },
  { name: 'Smith Machine Overhead Press',                 muscle: 'shoulders', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Smith Machine Behind-Neck Press',              muscle: 'shoulders', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Handstand Push-up',                            muscle: 'shoulders', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Pike Push-up',                                 muscle: 'shoulders', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Kettlebell Press',                             muscle: 'shoulders', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Kettlebell Lateral Raise',                     muscle: 'shoulders', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] } },
  { name: 'Kettlebell Upright Row',                       muscle: 'shoulders', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['side-delts', 'traps'], secondary: ['front-delts'] } },
  { name: 'Band Lateral Raise',                           muscle: 'shoulders', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] } },
  { name: 'Band Face Pull',                               muscle: 'shoulders', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] } },
  { name: 'Band Pull-Apart (Shoulders)',                  muscle: 'shoulders', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] } },
  { name: 'Landmine Press (Shoulders)',                   muscle: 'shoulders', equipment: 'Landmine',       type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] } },
  { name: 'Landmine Lateral Raise',                       muscle: 'shoulders', equipment: 'Landmine',       type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] } },

  // ===== ARMS (45) =====
  { name: 'Barbell Curl',                                 muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'EZ-Bar Curl',                                  muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Preacher Curl (Barbell)',                      muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Reverse Barbell Curl',                         muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Drag Curl',                                    muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Dumbbell Curl',                                muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Hammer Curl',                                  muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Incline Dumbbell Curl',                        muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Concentration Curl',                           muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Preacher Curl (Dumbbell)',                    muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Zottman Curl',                                 muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Cross-Body Curl',                              muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Cable Curl',                                   muscle: 'arms', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Cable Hammer Curl',                            muscle: 'arms', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Overhead Cable Curl',                          muscle: 'arms', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Machine Preacher Curl',                        muscle: 'arms', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms', 'lats'] } },
  { name: 'Machine Curl',                                 muscle: 'arms', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms', 'lats'] } },
  { name: 'Kettlebell Curl',                              muscle: 'arms', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Band Curl',                                    muscle: 'arms', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Skull Crushers',                               muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'EZ-Bar Skull Crushers',                        muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Close-Grip Bench Press (Triceps)',             muscle: 'arms', equipment: 'Barbell', type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'JM Press',                                     muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Dumbbell Tricep Extension',                    muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Overhead Dumbbell Extension',                  muscle: 'arms', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Dumbbell Kickback',                            muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Tate Press',                                   muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Tricep Pushdown',                              muscle: 'arms', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Overhead Cable Extension',                     muscle: 'arms', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Reverse Grip Pushdown',                        muscle: 'arms', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Single Arm Pushdown',                          muscle: 'arms', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Cable Kickback',                               muscle: 'arms', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Tricep Dip Machine',                           muscle: 'arms', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Wrist Curl',                                   muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['forearms'], secondary: [] } },
  { name: 'Reverse Wrist Curl',                           muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['forearms'], secondary: [] } },
  { name: 'Dumbbell Wrist Curl',                          muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['forearms'], secondary: [] } },
  { name: "Farmer's Walk",                                muscle: 'arms', equipment: 'Dumbbell',      type: 'distance_time', muscles: { primary: ['forearms'], secondary: [] } },
  { name: 'Dips',                                         muscle: 'arms', equipment: 'Bodyweight',     type: 'bw_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Bench Dips',                                  muscle: 'arms', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Diamond Push-ups (Triceps)',                   muscle: 'arms', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Chin-ups (Arms focus)',                        muscle: 'arms', equipment: 'Bodyweight',     type: 'bw_reps', muscles: { primary: ['biceps'], secondary: ['forearms', 'lats'] } },
  { name: 'Band Pushdown',                                muscle: 'arms', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },
  { name: 'Band Curl (Arms)',                             muscle: 'arms', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] } },
  { name: 'Kettlebell Tricep Extension',                  muscle: 'arms', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] } },

  // ===== CORE (31) =====
  { name: 'Plank',                                       muscle: 'core', equipment: 'Bodyweight',     type: 'time_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Side Plank',                                  muscle: 'core', equipment: 'Bodyweight',     type: 'time_only', muscles: { primary: ['obliques'], secondary: ['abs'] } },
  { name: 'Dead Bug',                                    muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Bird Dog',                                    muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Crunch',                                      muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Bicycle Crunch',                              muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Reverse Crunch',                              muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Sit-up',                                      muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'V-up',                                        muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Toe Touch',                                   muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Mountain Climber',                            muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Hanging Leg Raise',                            muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Hanging Knee Raise',                           muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Lying Leg Raise',                              muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Flutter Kicks',                                muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Scissor Kicks',                                muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Ab Wheel Rollout',                             muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Dragon Flag',                                 muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'L-Sit',                                       muscle: 'core', equipment: 'Bodyweight',     type: 'time_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Hollow Body Hold',                            muscle: 'core', equipment: 'Bodyweight',     type: 'time_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Cable Woodchop',                              muscle: 'core', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['obliques'], secondary: ['abs'] } },
  { name: 'Cable Crunch',                                muscle: 'core', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Pallof Press',                                muscle: 'core', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['obliques', 'abs'], secondary: [] } },
  { name: 'Cable Rotation',                               muscle: 'core', equipment: 'Cable',          type: 'weight_reps', muscles: { primary: ['obliques'], secondary: ['abs'] } },
  { name: 'Ab Machine Crunch',                            muscle: 'core', equipment: 'Machine',        type: 'weight_reps', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Decline Sit-up',                               muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Russian Twist',                               muscle: 'core', equipment: 'Dumbbell',       type: 'weight_reps', muscles: { primary: ['obliques'], secondary: ['abs'] } },
  { name: 'Weighted Plank',                               muscle: 'core', equipment: 'Barbell',        type: 'time_only', muscles: { primary: ['abs'], secondary: ['obliques'] } },
  { name: 'Kettlebell Windmill',                          muscle: 'core', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['obliques'], secondary: ['abs'] } },
  { name: 'Turkish Get-up',                               muscle: 'core', equipment: 'Kettlebell',     type: 'weight_reps', muscles: { primary: ['abs', 'obliques'], secondary: ['shoulders', 'glutes'] } },
  { name: 'Band Anti-Rotation',                           muscle: 'core', equipment: 'Band',           type: 'weight_reps', muscles: { primary: ['obliques'], secondary: ['abs'] } },

  // ===== CARDIO (35) =====
  { name: 'Treadmill Running',                            muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Treadmill Walking',                            muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Treadmill Incline Walk',                       muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Stationary Bike',                              muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Spin Bike',                                    muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Recumbent Bike',                               muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Assault Bike',                                 muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Rowing Machine',                               muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Elliptical',                                   muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Stair Climber',                                muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'StairMaster',                                  muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Ski Erg',                                      muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: "Jacob's Ladder",                               muscle: 'cardio', equipment: 'Machine',      type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Outdoor Running',                              muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Outdoor Walking',                              muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Outdoor Cycling',                              muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Swimming',                                     muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Hiking',                                      muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Jump Rope',                                    muscle: 'cardio', equipment: 'Bodyweight',   type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Jumping Jacks',                                muscle: 'cardio', equipment: 'Bodyweight',   type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Burpees',                                      muscle: 'cardio', equipment: 'Bodyweight',   type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Box Jump',                                     muscle: 'cardio', equipment: 'Bodyweight',   type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Battle Ropes',                                 muscle: 'cardio', equipment: 'Other',        type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Sled Push',                                    muscle: 'cardio', equipment: 'Other',        type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Sled Pull',                                    muscle: 'cardio', equipment: 'Other',        type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Tire Flip',                                    muscle: 'cardio', equipment: 'Other',        type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Kettlebell Swing (Cardio)',                    muscle: 'cardio', equipment: 'Kettlebell',   type: 'weight_reps', muscles: { primary: [], secondary: [] } },
  { name: 'Kettlebell Snatch',                            muscle: 'cardio', equipment: 'Kettlebell',   type: 'weight_reps', muscles: { primary: [], secondary: [] } },
  { name: 'Kettlebell Clean & Press',                     muscle: 'cardio', equipment: 'Kettlebell',   type: 'weight_reps', muscles: { primary: [], secondary: [] } },
  { name: 'Barbell Thruster',                             muscle: 'cardio', equipment: 'Barbell',      type: 'weight_reps', muscles: { primary: [], secondary: [] } },
  { name: 'Dumbbell Thruster',                            muscle: 'cardio', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: [], secondary: [] } },
  { name: 'Man Maker',                                    muscle: 'cardio', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: [], secondary: [] } },
  { name: 'Devil Press',                                  muscle: 'cardio', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: [], secondary: [] } },
  { name: 'Bear Crawl',                                   muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time', muscles: { primary: [], secondary: [] } },
  { name: 'Sprints',                                      muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time', muscles: { primary: [], secondary: [] } },

  // ===== MOBILITY (30) =====
  { name: 'Foam Roll - Upper Back',                       muscle: 'mobility', equipment: 'Other',      type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Foam Roll - Quads',                            muscle: 'mobility', equipment: 'Other',      type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Foam Roll - Hamstrings',                       muscle: 'mobility', equipment: 'Other',      type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Foam Roll - IT Band',                          muscle: 'mobility', equipment: 'Other',      type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Foam Roll - Lats',                             muscle: 'mobility', equipment: 'Other',      type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Foam Roll - Calves',                           muscle: 'mobility', equipment: 'Other',      type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Hip Flexor Stretch',                           muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Pigeon Stretch',                               muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: '90/90 Hip Stretch',                            muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Couch Stretch',                                muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: "World's Greatest Stretch",                    muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Cat-Cow',                                      muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Thoracic Spine Rotation',                      muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Shoulder Dislocates',                          muscle: 'mobility', equipment: 'Band',       type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Band Pull-Apart (Warmup)',                     muscle: 'mobility', equipment: 'Band',       type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Wall Slide',                                   muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Scapular Push-up',                             muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Face-the-Wall Squat',                          muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Ankle Dorsiflexion Stretch',                   muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Hamstring Stretch',                            muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Quad Stretch',                                 muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Calf Stretch',                                 muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Chest Stretch (Doorway)',                      muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Lat Stretch',                                  muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Tricep Stretch',                               muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Neck Stretch',                                  muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] } },
  { name: 'Wrist Circles',                                muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Leg Swings',                                   muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'Arm Circles',                                 muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] } },
  { name: 'TRX Squat Stretch',                            muscle: 'mobility', equipment: 'TRX',        type: 'time_only', muscles: { primary: [], secondary: [] } },
]

// Exercise type labels
export const TYPE_LABELS = {
  weight_reps: 'Weight + Reps',
  bw_reps: 'BW ± kg',
  reps_only: 'Reps only',
  time_only: 'Time',
  distance_time: 'Distance + Time',
}

// Filter exercises by criteria
export function filterExercises(allExercises, { search = '', muscles = [], equipment = 'all', myOnly = false }) {
  return allExercises.filter(ex => {
    if (search && !ex.name.toLowerCase().includes(search.toLowerCase())) return false
    if (myOnly && !ex.isCustom) return false
    if (muscles.length > 0 && !muscles.includes(ex.muscle)) return false
    if (equipment !== 'all' && ex.equipment !== equipment) return false
    return true
  })
}

// Group exercises by muscle
export function groupByMuscle(exercises) {
  const groups = {}
  const order = ['chest', 'back', 'legs', 'shoulders', 'arms', 'core', 'cardio', 'mobility']
  for (const m of order) groups[m] = []
  for (const ex of exercises) {
    if (!groups[ex.muscle]) groups[ex.muscle] = []
    groups[ex.muscle].push(ex)
  }
  return Object.entries(groups).filter(([, exs]) => exs.length > 0)
}