// Muscle group definitions with colors
export const MUSCLE_GROUPS = {
  chest:     { label: 'Chest',     color: '#7B7BFF', bg: 'rgba(123,123,255,0.1)' },
  back:      { label: 'Back',      color: '#5BF5A0', bg: 'rgba(91,245,160,0.1)' },
  legs:      { label: 'Legs',      color: '#FFAA50', bg: 'rgba(255,170,80,0.1)' },
  shoulders: { label: 'Shoulders', color: '#4ECDC4', bg: 'rgba(78,205,196,0.1)' },
  arms:      { label: 'Arms',      color: '#ff6b6b', bg: 'rgba(255,107,107,0.1)' },
  core:      { label: 'Core',      color: '#C8A0FF', bg: 'rgba(200,160,255,0.1)' },
  cardio:    { label: 'Cardio',    color: '#FFD93D', bg: 'rgba(255,217,61,0.1)' },
  mobility:  { label: 'Mobility',  color: '#78D5D7', bg: 'rgba(120,213,215,0.1)' },
}

export const EQUIPMENT_TYPES = ['Barbell', 'Dumbbell', 'Cable', 'Machine', 'Bodyweight', 'Kettlebell', 'Band', 'TRX', 'Smith Machine', 'Landmine', 'Other']

// Default exercise library (300 exercises)
export const DEFAULT_EXERCISES = [
  // ===== CHEST (30) =====
  { name: 'Barbell Bench Press',         muscle: 'chest', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Incline Barbell Bench Press', muscle: 'chest', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Decline Barbell Bench Press', muscle: 'chest', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Close-Grip Bench Press',      muscle: 'chest', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Floor Press',                 muscle: 'chest', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Dumbbell Bench Press',        muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Incline Dumbbell Press',      muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Decline Dumbbell Press',      muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Flyes',             muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Incline Dumbbell Flyes',     muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Pullover',          muscle: 'chest', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Cable Flyes',                muscle: 'chest', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Crossover',            muscle: 'chest', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Low Cable Flye',             muscle: 'chest', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Machine Chest Press',        muscle: 'chest', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Incline Machine Press',      muscle: 'chest', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Pec Deck',                   muscle: 'chest', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Smith Machine Bench Press',  muscle: 'chest', equipment: 'Smith Machine',  type: 'weight_reps' },
  { name: 'Smith Machine Incline Press',muscle: 'chest', equipment: 'Smith Machine',  type: 'weight_reps' },
  { name: 'Chest Dip',                  muscle: 'chest', equipment: 'Bodyweight',     type: 'bw_reps' },
  { name: 'Push-ups',                   muscle: 'chest', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Incline Push-ups',           muscle: 'chest', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Decline Push-ups',           muscle: 'chest', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Diamond Push-ups',           muscle: 'chest', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Wide Push-ups',              muscle: 'chest', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Landmine Press',             muscle: 'chest', equipment: 'Landmine',       type: 'weight_reps' },
  { name: 'Single Arm Landmine Press',  muscle: 'chest', equipment: 'Landmine',       type: 'weight_reps' },
  { name: 'Band Chest Press',           muscle: 'chest', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Band Flyes',                 muscle: 'chest', equipment: 'Band',           type: 'weight_reps' },
  { name: 'TRX Push-up',               muscle: 'chest', equipment: 'TRX',            type: 'reps_only' },

  // ===== BACK (39) =====
  { name: 'Barbell Row',                muscle: 'back', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Pendlay Row',                muscle: 'back', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Conventional Deadlift',      muscle: 'back', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Sumo Deadlift',              muscle: 'back', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Rack Pull',                  muscle: 'back', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'T-Bar Row',                  muscle: 'back', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Barbell Shrug',              muscle: 'back', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Dumbbell Row',               muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Shrug',             muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Pullover (Back)',   muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Incline Dumbbell Row',       muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Kroc Row',                   muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Lat Pulldown',               muscle: 'back', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Close-Grip Pulldown',        muscle: 'back', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Wide-Grip Pulldown',         muscle: 'back', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Straight Arm Pulldown',      muscle: 'back', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Seated Cable Row',           muscle: 'back', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Face Pull',                  muscle: 'back', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Single Arm Cable Row',       muscle: 'back', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Shrug',                muscle: 'back', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Machine Row',                muscle: 'back', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Chest-Supported Row',        muscle: 'back', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Reverse Grip Machine Row',   muscle: 'back', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Machine Shrug',              muscle: 'back', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Smith Machine Row',          muscle: 'back', equipment: 'Smith Machine',  type: 'weight_reps' },
  { name: 'Smith Machine Shrug',        muscle: 'back', equipment: 'Smith Machine',  type: 'weight_reps' },
  { name: 'Pull-ups',                   muscle: 'back', equipment: 'Bodyweight',     type: 'bw_reps' },
  { name: 'Chin-ups',                   muscle: 'back', equipment: 'Bodyweight',     type: 'bw_reps' },
  { name: 'Wide-Grip Pull-ups',         muscle: 'back', equipment: 'Bodyweight',     type: 'bw_reps' },
  { name: 'Neutral-Grip Pull-ups',      muscle: 'back', equipment: 'Bodyweight',     type: 'bw_reps' },
  { name: 'Inverted Row',               muscle: 'back', equipment: 'Bodyweight',     type: 'bw_reps' },
  { name: 'Back Extension',             muscle: 'back', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Landmine Row',               muscle: 'back', equipment: 'Landmine',       type: 'weight_reps' },
  { name: 'Meadows Row',                muscle: 'back', equipment: 'Landmine',       type: 'weight_reps' },
  { name: 'TRX Row',                    muscle: 'back', equipment: 'TRX',            type: 'reps_only' },
  { name: 'Band Pull-Apart',            muscle: 'back', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Band Row',                   muscle: 'back', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Kettlebell Row',             muscle: 'back', equipment: 'Kettlebell',     type: 'weight_reps' },
  { name: 'Kettlebell Swing',           muscle: 'back', equipment: 'Kettlebell',     type: 'weight_reps' },

  // ===== LEGS (56) =====
  { name: 'Barbell Back Squat',         muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Front Squat',                muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Zercher Squat',              muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Pause Squat',                muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Box Squat',                  muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Romanian Deadlift',          muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Stiff-Leg Deadlift',         muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Good Morning',               muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Barbell Lunge',              muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Barbell Hip Thrust',         muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Barbell Calf Raise',         muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Dumbbell Squat',             muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Goblet Squat',               muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Romanian Deadlift', muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Lunge',             muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Walking Lunge',              muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Bulgarian Split Squat',      muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Step-up',           muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Calf Raise',        muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Hip Thrust',        muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Cable Pull-Through',         muscle: 'legs', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Kickback',             muscle: 'legs', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Hip Adduction',        muscle: 'legs', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Hip Abduction',        muscle: 'legs', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Leg Press',                  muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Hack Squat',                 muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Leg Extension',              muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Seated Leg Curl',            muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Lying Leg Curl',             muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Standing Leg Curl',          muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Hip Adductor Machine',       muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Hip Abductor Machine',       muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Glute Drive Machine',        muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Seated Calf Raise',          muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Standing Calf Raise',        muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Pendulum Squat',             muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Belt Squat',                 muscle: 'legs', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Smith Machine Squat',        muscle: 'legs', equipment: 'Smith Machine',  type: 'weight_reps' },
  { name: 'Smith Machine Romanian Deadlift', muscle: 'legs', equipment: 'Smith Machine', type: 'weight_reps' },
  { name: 'Smith Machine Lunge',        muscle: 'legs', equipment: 'Smith Machine',  type: 'weight_reps' },
  { name: 'Smith Machine Hip Thrust',   muscle: 'legs', equipment: 'Smith Machine',  type: 'weight_reps' },
  { name: 'Smith Machine Calf Raise',   muscle: 'legs', equipment: 'Smith Machine',  type: 'weight_reps' },
  { name: 'Bodyweight Squat',           muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Pistol Squat',               muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Jump Squat',                 muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Bodyweight Lunge',           muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Glute Bridge',               muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Nordic Hamstring Curl',      muscle: 'legs', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Wall Sit',                   muscle: 'legs', equipment: 'Bodyweight',     type: 'time_only' },
  { name: 'Kettlebell Goblet Squat',    muscle: 'legs', equipment: 'Kettlebell',     type: 'weight_reps' },
  { name: 'Kettlebell Deadlift',        muscle: 'legs', equipment: 'Kettlebell',     type: 'weight_reps' },
  { name: 'Kettlebell Lunge',           muscle: 'legs', equipment: 'Kettlebell',     type: 'weight_reps' },
  { name: 'Band Squat',                 muscle: 'legs', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Band Leg Curl',              muscle: 'legs', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Landmine Squat',             muscle: 'legs', equipment: 'Landmine',       type: 'weight_reps' },
  { name: 'Landmine Romanian Deadlift', muscle: 'legs', equipment: 'Landmine',       type: 'weight_reps' },

  // ===== SHOULDERS (35) =====
  { name: 'Barbell Overhead Press',     muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Push Press',                 muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Behind-the-Neck Press',      muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Barbell Upright Row',        muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Barbell Front Raise',        muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Bradford Press',             muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Dumbbell Shoulder Press',    muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Arnold Press',               muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Lateral Raise',              muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Front Raise',                muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Upright Row',       muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Reverse Flye',               muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Dumbbell Shrug (Shoulders)', muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Lu Raise',                   muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Cable Lateral Raise',        muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Front Raise',          muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Reverse Flye',         muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Upright Row',          muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Face Pull',            muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Shoulder Press',       muscle: 'shoulders', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Machine Shoulder Press',     muscle: 'shoulders', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Machine Lateral Raise',      muscle: 'shoulders', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Reverse Pec Deck',           muscle: 'shoulders', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Smith Machine Overhead Press', muscle: 'shoulders', equipment: 'Smith Machine', type: 'weight_reps' },
  { name: 'Smith Machine Behind-Neck Press', muscle: 'shoulders', equipment: 'Smith Machine', type: 'weight_reps' },
  { name: 'Handstand Push-up',          muscle: 'shoulders', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Pike Push-up',               muscle: 'shoulders', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Kettlebell Press',            muscle: 'shoulders', equipment: 'Kettlebell',     type: 'weight_reps' },
  { name: 'Kettlebell Lateral Raise',    muscle: 'shoulders', equipment: 'Kettlebell',     type: 'weight_reps' },
  { name: 'Kettlebell Upright Row',      muscle: 'shoulders', equipment: 'Kettlebell',     type: 'weight_reps' },
  { name: 'Band Lateral Raise',          muscle: 'shoulders', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Band Face Pull',              muscle: 'shoulders', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Band Pull-Apart (Shoulders)', muscle: 'shoulders', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Landmine Press (Shoulders)',   muscle: 'shoulders', equipment: 'Landmine',       type: 'weight_reps' },
  { name: 'Landmine Lateral Raise',      muscle: 'shoulders', equipment: 'Landmine',       type: 'weight_reps' },

  // ===== ARMS (45) =====
  { name: 'Barbell Curl',               muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'EZ-Bar Curl',                muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Preacher Curl (Barbell)',     muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Reverse Barbell Curl',       muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Drag Curl',                  muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Dumbbell Curl',              muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Hammer Curl',                muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Incline Dumbbell Curl',      muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Concentration Curl',         muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Preacher Curl (Dumbbell)',   muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Zottman Curl',               muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Cross-Body Curl',            muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Cable Curl',                 muscle: 'arms', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Hammer Curl',          muscle: 'arms', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Overhead Cable Curl',        muscle: 'arms', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Machine Preacher Curl',      muscle: 'arms', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Machine Curl',               muscle: 'arms', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Kettlebell Curl',            muscle: 'arms', equipment: 'Kettlebell',     type: 'weight_reps' },
  { name: 'Band Curl',                  muscle: 'arms', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Skull Crushers',             muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'EZ-Bar Skull Crushers',      muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Close-Grip Bench Press (Triceps)', muscle: 'arms', equipment: 'Barbell', type: 'weight_reps' },
  { name: 'JM Press',                   muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Dumbbell Tricep Extension',  muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Overhead Dumbbell Extension', muscle: 'arms', equipment: 'Dumbbell',     type: 'weight_reps' },
  { name: 'Dumbbell Kickback',          muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Tate Press',                 muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: 'Tricep Pushdown',            muscle: 'arms', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Overhead Cable Extension',   muscle: 'arms', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Reverse Grip Pushdown',      muscle: 'arms', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Single Arm Pushdown',        muscle: 'arms', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Kickback',             muscle: 'arms', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Tricep Dip Machine',         muscle: 'arms', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Wrist Curl',                 muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Reverse Wrist Curl',         muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps' },
  { name: 'Dumbbell Wrist Curl',        muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps' },
  { name: "Farmer's Walk",              muscle: 'arms', equipment: 'Dumbbell',      type: 'distance_time' },
  { name: 'Dips',                       muscle: 'arms', equipment: 'Bodyweight',     type: 'bw_reps' },
  { name: 'Bench Dips',                 muscle: 'arms', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Diamond Push-ups (Triceps)', muscle: 'arms', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Chin-ups (Arms focus)',      muscle: 'arms', equipment: 'Bodyweight',     type: 'bw_reps' },
  { name: 'Band Pushdown',              muscle: 'arms', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Band Curl (Arms)',           muscle: 'arms', equipment: 'Band',           type: 'weight_reps' },
  { name: 'Kettlebell Tricep Extension', muscle: 'arms', equipment: 'Kettlebell',    type: 'weight_reps' },

  // ===== CORE (31) =====
  { name: 'Plank',                      muscle: 'core', equipment: 'Bodyweight',     type: 'time_only' },
  { name: 'Side Plank',                 muscle: 'core', equipment: 'Bodyweight',     type: 'time_only' },
  { name: 'Dead Bug',                   muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Bird Dog',                   muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Crunch',                     muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Bicycle Crunch',             muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Reverse Crunch',             muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Sit-up',                     muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'V-up',                       muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Toe Touch',                  muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Mountain Climber',           muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Hanging Leg Raise',          muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Hanging Knee Raise',         muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Lying Leg Raise',            muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Flutter Kicks',              muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Scissor Kicks',              muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Ab Wheel Rollout',           muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Dragon Flag',                muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'L-Sit',                      muscle: 'core', equipment: 'Bodyweight',     type: 'time_only' },
  { name: 'Hollow Body Hold',           muscle: 'core', equipment: 'Bodyweight',     type: 'time_only' },
  { name: 'Cable Woodchop',             muscle: 'core', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Crunch',               muscle: 'core', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Pallof Press',               muscle: 'core', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Cable Rotation',             muscle: 'core', equipment: 'Cable',          type: 'weight_reps' },
  { name: 'Ab Machine Crunch',          muscle: 'core', equipment: 'Machine',        type: 'weight_reps' },
  { name: 'Decline Sit-up',             muscle: 'core', equipment: 'Bodyweight',     type: 'reps_only' },
  { name: 'Russian Twist',              muscle: 'core', equipment: 'Dumbbell',       type: 'weight_reps' },
  { name: 'Weighted Plank',             muscle: 'core', equipment: 'Barbell',        type: 'time_only' },
  { name: 'Kettlebell Windmill',        muscle: 'core', equipment: 'Kettlebell',     type: 'weight_reps' },
  { name: 'Turkish Get-up',             muscle: 'core', equipment: 'Kettlebell',     type: 'weight_reps' },
  { name: 'Band Anti-Rotation',         muscle: 'core', equipment: 'Band',           type: 'weight_reps' },

  // ===== CARDIO (35) =====
  { name: 'Treadmill Running',          muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Treadmill Walking',          muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Treadmill Incline Walk',     muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Stationary Bike',            muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Spin Bike',                  muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Recumbent Bike',             muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Assault Bike',               muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Rowing Machine',             muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Elliptical',                 muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Stair Climber',              muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'StairMaster',                muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Ski Erg',                    muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: "Jacob's Ladder",             muscle: 'cardio', equipment: 'Machine',      type: 'distance_time' },
  { name: 'Outdoor Running',            muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time' },
  { name: 'Outdoor Walking',            muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time' },
  { name: 'Outdoor Cycling',            muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time' },
  { name: 'Swimming',                   muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time' },
  { name: 'Hiking',                     muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time' },
  { name: 'Jump Rope',                  muscle: 'cardio', equipment: 'Bodyweight',   type: 'time_only' },
  { name: 'Jumping Jacks',              muscle: 'cardio', equipment: 'Bodyweight',   type: 'time_only' },
  { name: 'Burpees',                    muscle: 'cardio', equipment: 'Bodyweight',   type: 'reps_only' },
  { name: 'Box Jump',                   muscle: 'cardio', equipment: 'Bodyweight',   type: 'reps_only' },
  { name: 'Battle Ropes',               muscle: 'cardio', equipment: 'Other',        type: 'time_only' },
  { name: 'Sled Push',                  muscle: 'cardio', equipment: 'Other',        type: 'distance_time' },
  { name: 'Sled Pull',                  muscle: 'cardio', equipment: 'Other',        type: 'distance_time' },
  { name: 'Tire Flip',                  muscle: 'cardio', equipment: 'Other',        type: 'reps_only' },
  { name: 'Kettlebell Swing (Cardio)',  muscle: 'cardio', equipment: 'Kettlebell',   type: 'weight_reps' },
  { name: 'Kettlebell Snatch',          muscle: 'cardio', equipment: 'Kettlebell',   type: 'weight_reps' },
  { name: 'Kettlebell Clean & Press',   muscle: 'cardio', equipment: 'Kettlebell',   type: 'weight_reps' },
  { name: 'Barbell Thruster',           muscle: 'cardio', equipment: 'Barbell',      type: 'weight_reps' },
  { name: 'Dumbbell Thruster',          muscle: 'cardio', equipment: 'Dumbbell',     type: 'weight_reps' },
  { name: 'Man Maker',                  muscle: 'cardio', equipment: 'Dumbbell',     type: 'weight_reps' },
  { name: 'Devil Press',                muscle: 'cardio', equipment: 'Dumbbell',     type: 'weight_reps' },
  { name: 'Bear Crawl',                 muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time' },
  { name: 'Sprints',                    muscle: 'cardio', equipment: 'Bodyweight',   type: 'distance_time' },

  // ===== MOBILITY (30) =====
  { name: 'Foam Roll - Upper Back',     muscle: 'mobility', equipment: 'Other',      type: 'time_only' },
  { name: 'Foam Roll - Quads',          muscle: 'mobility', equipment: 'Other',      type: 'time_only' },
  { name: 'Foam Roll - Hamstrings',     muscle: 'mobility', equipment: 'Other',      type: 'time_only' },
  { name: 'Foam Roll - IT Band',        muscle: 'mobility', equipment: 'Other',      type: 'time_only' },
  { name: 'Foam Roll - Lats',           muscle: 'mobility', equipment: 'Other',      type: 'time_only' },
  { name: 'Foam Roll - Calves',         muscle: 'mobility', equipment: 'Other',      type: 'time_only' },
  { name: 'Hip Flexor Stretch',         muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Pigeon Stretch',             muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: '90/90 Hip Stretch',          muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Couch Stretch',              muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: "World's Greatest Stretch",   muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Cat-Cow',                    muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only' },
  { name: 'Thoracic Spine Rotation',    muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only' },
  { name: 'Shoulder Dislocates',        muscle: 'mobility', equipment: 'Band',       type: 'reps_only' },
  { name: 'Band Pull-Apart (Warmup)',   muscle: 'mobility', equipment: 'Band',       type: 'reps_only' },
  { name: 'Wall Slide',                 muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only' },
  { name: 'Scapular Push-up',           muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only' },
  { name: 'Face-the-Wall Squat',        muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only' },
  { name: 'Ankle Dorsiflexion Stretch', muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Hamstring Stretch',          muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Quad Stretch',               muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Calf Stretch',               muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Chest Stretch (Doorway)',    muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Lat Stretch',                muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Tricep Stretch',             muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Neck Stretch',               muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only' },
  { name: 'Wrist Circles',              muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only' },
  { name: 'Leg Swings',                 muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only' },
  { name: 'Arm Circles',                muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only' },
  { name: 'TRX Squat Stretch',          muscle: 'mobility', equipment: 'TRX',        type: 'time_only' },
]

// Exercise type labels
export const TYPE_LABELS = {
  weight_reps: 'Weight + Reps',
  bw_reps: 'BW ± kg',
  reps_only: 'Reps only',
  time_only: 'Time',
  distance_time: 'Distance + Time',
}

// Filter exercises by criteria
export function filterExercises(allExercises, { search = '', muscles = [], equipment = 'all', myOnly = false }) {
  return allExercises.filter(ex => {
    if (search && !ex.name.toLowerCase().includes(search.toLowerCase())) return false
    if (myOnly && !ex.isCustom) return false
    if (muscles.length > 0 && !muscles.includes(ex.muscle)) return false
    if (equipment !== 'all' && ex.equipment !== equipment) return false
    return true
  })
}

// Group exercises by muscle
export function groupByMuscle(exercises) {
  const groups = {}
  const order = ['chest', 'back', 'legs', 'shoulders', 'arms', 'core', 'cardio', 'mobility']
  for (const m of order) groups[m] = []
  for (const ex of exercises) {
    if (!groups[ex.muscle]) groups[ex.muscle] = []
    groups[ex.muscle].push(ex)
  }
  return Object.entries(groups).filter(([, exs]) => exs.length > 0)
}