// Muscle group definitions with colors — each group has a unique color (used in exercise picker, home card, muscle map, etc.)
export const MUSCLE_GROUPS = {
  chest:     { label: 'Chest',     color: '#7B7BFF', bg: 'rgba(123,123,255,0.1)' },
  back:      { label: 'Back',      color: '#5BF5A0', bg: 'rgba(91,245,160,0.1)' },
  legs:      { label: 'Legs',      color: '#FFAA50', bg: 'rgba(255,170,80,0.1)' },
  shoulders: { label: 'Shoulders', color: '#4ECDC4', bg: 'rgba(78,205,196,0.1)' },
  arms:      { label: 'Arms',      color: '#ff6b6b', bg: 'rgba(255,107,107,0.1)' },
  core:      { label: 'Core',      color: '#C8A0FF', bg: 'rgba(200,160,255,0.1)' },
  cardio:    { label: 'Cardio',    color: '#FFD93D', bg: 'rgba(255,217,61,0.1)' },
  mobility:  { label: 'Mobility',  color: '#F59E0B', bg: 'rgba(245,158,11,0.12)' },
}

// The 16 muscle slugs used for recovery tracking and muscle maps.
export const MUSCLE_SLUGS = [
  'chest', 'front-delts', 'side-delts', 'rear-delts',
  'triceps', 'biceps', 'forearms',
  'back', 'lats', 'traps', 'lower-back',
  'abs', 'obliques',
  'quads', 'hamstrings', 'glutes', 'calves',
]

/** Slug → MUSCLE_GROUPS key for display/color when showing slug tags */
export const SLUG_TO_GROUP = {
  chest: 'chest', 'front-delts': 'shoulders', 'side-delts': 'shoulders', 'rear-delts': 'shoulders',
  triceps: 'arms', biceps: 'arms', forearms: 'arms',
  back: 'back', lats: 'back', traps: 'back', 'lower-back': 'back',
  abs: 'core', obliques: 'core',
  quads: 'legs', hamstrings: 'legs', glutes: 'legs', calves: 'legs',
}

/** Returns unique slugs (primary + secondary) for an exercise from library. */
export function getExerciseSlugs(lib) {
  if (!lib) return []
  const m = lib.muscles
  if (m) {
    const hasSlugs = (m.primary?.length || 0) + (m.secondary?.length || 0) > 0
    if (hasSlugs) {
      const set = new Set([...(m.primary || []), ...(m.secondary || [])])
      return [...set]
    }
    return []
  }
  if (lib.muscle) return [lib.muscle]
  return []
}

export const EQUIPMENT_TYPES = ['Barbell', 'Dumbbell', 'Cable', 'Machine', 'Bodyweight', 'Kettlebell', 'Band', 'TRX', 'Smith Machine', 'Landmine', 'Other']

// Default exercise library
export const DEFAULT_EXERCISES = [
  // ===== CHEST =====
  { name: 'Barbell Bench Press',         muscle: 'chest', equipment: 'Barbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Bench Press', 'Flat Bench Press', 'Bench Press (Barbell)', 'Flat Bench', 'BB Bench Press'] },
  { name: 'Wide Grip Bench Press',        muscle: 'chest', equipment: 'Barbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Bench Press - Wide Grip (Barbell)', 'Wide Grip Bench', 'Wide Bench Press'] },
  { name: 'Incline Barbell Bench Press',  muscle: 'chest', equipment: 'Barbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Incline Bench Press', 'Incline Bench Press (Barbell)', 'Incline BB Press'] },
  { name: 'Decline Barbell Bench Press',  muscle: 'chest', equipment: 'Barbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Decline Bench Press', 'Decline Bench Press (Barbell)'] },
  { name: 'Close-Grip Bench Press',       muscle: 'chest', equipment: 'Barbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['triceps', 'front-delts'] },
    aliases: ['Close Grip Bench', 'CGBP'] },
  { name: 'Floor Press',                  muscle: 'chest', equipment: 'Barbell',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Barbell Floor Press'] },
  { name: 'Dumbbell Bench Press',         muscle: 'chest', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['DB Bench Press', 'Dumbbell Press', 'Bench Press (Dumbbell)'] },
  { name: 'Incline Dumbbell Press',       muscle: 'chest', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Incline DB Press', 'Incline Dumbbell Bench Press', 'Incline Bench Press (Dumbbell)', 'Incline Press (Dumbbell)'] },
  { name: 'Decline Dumbbell Press',       muscle: 'chest', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Decline DB Press', 'Decline Press (Dumbbell)'] },
  { name: 'Dumbbell Flyes',               muscle: 'chest', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] },
    aliases: ['DB Flyes', 'Dumbbell Fly', 'Chest Fly (Dumbbell)', 'DB Fly', 'Flat Dumbbell Fly'] },
  { name: 'Incline Dumbbell Flyes',       muscle: 'chest', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] },
    aliases: ['Incline DB Flyes', 'Incline Dumbbell Fly'] },
  { name: 'Dumbbell Pullover',            muscle: 'chest', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['lats'] },
    aliases: ['DB Pullover', 'Pullover'] },
  { name: 'Hex Press',                    muscle: 'chest', equipment: 'Dumbbell',     type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Hex Press (Dumbbell)', 'Squeeze Press'] },
  { name: 'Cable Flyes',                  muscle: 'chest', equipment: 'Cable',        type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] },
    aliases: ['Cable Fly', 'Cable Flyes (Chest)', 'High Cable Fly', 'Cable Chest Fly'] },
  { name: 'Cable Crossover',              muscle: 'chest', equipment: 'Cable',        type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] },
    aliases: ['Cable Cross Over', 'Crossover'] },
  { name: 'Low Cable Flye',               muscle: 'chest', equipment: 'Cable',        type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] },
    aliases: ['Low Cable Fly', 'Low Pulley Fly'] },
  { name: 'Machine Chest Press',          muscle: 'chest', equipment: 'Machine',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Chest Press (Machine)', 'Chest Press', 'Machine Press'] },
  { name: 'Incline Machine Press',        muscle: 'chest', equipment: 'Machine',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Incline Chest Press (Machine)'] },
  { name: 'Pec Deck',                     muscle: 'chest', equipment: 'Machine',      type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] },
    aliases: ['Pec Deck Fly', 'Machine Fly', 'Machine Flyes'] },
  { name: 'Smith Machine Bench Press',    muscle: 'chest', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Bench Press (Smith Machine)', 'Smith Bench Press'] },
  { name: 'Smith Machine Incline Press',  muscle: 'chest', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Incline Bench Press (Smith Machine)', 'Smith Machine Incline Bench Press', 'Incline Smith Press'] },
  { name: 'Chest Dip',                    muscle: 'chest', equipment: 'Bodyweight',   type: 'bw_reps',     muscles: { primary: ['chest', 'triceps'], secondary: ['front-delts'] },
    aliases: ['Chest Dip (Assisted)', 'Triceps Dip (Assisted)', 'Dip', 'Assisted Dip', 'Weighted Dip'] },
  { name: 'Push-ups',                     muscle: 'chest', equipment: 'Bodyweight',   type: 'reps_only',   muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Push Up', 'Push-up', 'Pushup', 'Press Up'] },
  { name: 'Incline Push-ups',             muscle: 'chest', equipment: 'Bodyweight',   type: 'reps_only',   muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Incline Push Up', 'Incline Pushup'] },
  { name: 'Decline Push-ups',             muscle: 'chest', equipment: 'Bodyweight',   type: 'reps_only',   muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Decline Push Up', 'Decline Pushup'] },
  { name: 'Diamond Push-ups',             muscle: 'chest', equipment: 'Bodyweight',   type: 'reps_only',   muscles: { primary: ['chest'], secondary: ['triceps', 'front-delts'] },
    aliases: ['Diamond Push Up', 'Diamond Pushup'] },
  { name: 'Wide Push-ups',                muscle: 'chest', equipment: 'Bodyweight',   type: 'reps_only',   muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: ['Wide Push Up', 'Wide Pushup'] },
  { name: 'Landmine Press',               muscle: 'chest', equipment: 'Landmine',     type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: [] },
  { name: 'Single Arm Landmine Press',    muscle: 'chest', equipment: 'Landmine',     type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: [] },
  { name: 'Band Chest Press',             muscle: 'chest', equipment: 'Band',         type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: [] },
  { name: 'Band Flyes',                   muscle: 'chest', equipment: 'Band',         type: 'weight_reps', muscles: { primary: ['chest'], secondary: ['front-delts'] },
    aliases: [] },
  { name: 'TRX Push-up',                  muscle: 'chest', equipment: 'TRX',          type: 'reps_only',   muscles: { primary: ['chest'], secondary: ['front-delts', 'triceps'] },
    aliases: [] },

  // ===== BACK =====
  { name: 'Barbell Row',                  muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: ['Bent Over Row (Barbell)', 'Bent Over Row', 'BB Row', 'Barbell Bent Over Row', 'Overhand Row'] },
  { name: 'Pendlay Row',                  muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: [] },
  { name: 'Conventional Deadlift',        muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'glutes', 'hamstrings'], secondary: ['traps', 'quads'] },
    aliases: ['Deadlift', 'Deadlift (Barbell)', 'Barbell Deadlift'] },
  { name: 'Sumo Deadlift',                muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'glutes', 'hamstrings'], secondary: ['traps', 'quads'] },
    aliases: ['Sumo Deadlift (Barbell)'] },
  { name: 'Rack Pull',                    muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'glutes', 'hamstrings'], secondary: ['traps', 'quads'] },
    aliases: ['Rack Pulls'] },
  { name: 'T-Bar Row',                    muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: ['T Bar Row'] },
  { name: 'Barbell Shrug',                muscle: 'back', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['traps'], secondary: ['back'] },
    aliases: ['Shrug (Barbell)', 'Shrug'] },
  { name: 'Dumbbell Row',                 muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: ['One Arm Dumbbell Row', 'Single Arm Dumbbell Row', 'DB Row', 'Row (Dumbbell)'] },
  { name: 'Dumbbell Shrug',               muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['traps'], secondary: ['back'] },
    aliases: ['Shrug (Dumbbell)', 'DB Shrug'] },
  { name: 'Dumbbell Pullover (Back)',     muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['lats'], secondary: ['chest'] },
    aliases: [] },
  { name: 'Incline Dumbbell Row',         muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: [] },
  { name: 'Kroc Row',                     muscle: 'back', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: [] },
  { name: 'Lat Pulldown',                 muscle: 'back', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: ['Lat Pulldown (Cable)', 'Cable Lat Pulldown', 'Pull Down', 'Pulldown', 'Lat Pull Down'] },
  { name: 'Single Arm Lat Pulldown',      muscle: 'back', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: ['Lat Pulldown (Single Arm)', 'One Arm Lat Pulldown', 'Single Arm Pulldown'] },
  { name: 'Close-Grip Pulldown',          muscle: 'back', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: ['Close Grip Pulldown', 'Narrow Grip Pulldown'] },
  { name: 'Wide-Grip Pulldown',           muscle: 'back', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: ['Wide Grip Pulldown'] },
  { name: 'Straight Arm Pulldown',        muscle: 'back', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['lats'], secondary: ['triceps'] },
    aliases: ['Straight Arm Lat Pulldown'] },
  { name: 'Seated Cable Row',             muscle: 'back', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: ['Cable Row', 'Seated Row', 'Low Cable Row', 'Cable Seated Row', 'Row (Cable)'] },
  { name: 'Face Pull',                    muscle: 'back', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['rear-delts', 'traps'], secondary: ['back'] },
    aliases: ['Cable Face Pull', 'Rope Face Pull'] },
  { name: 'Single Arm Cable Row',         muscle: 'back', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: ['One Arm Cable Row'] },
  { name: 'Cable Shrug',                  muscle: 'back', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['traps'], secondary: ['back'] },
    aliases: [] },
  { name: 'Machine Row',                  muscle: 'back', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: ['Row (Machine)'] },
  { name: 'Chest-Supported Row',          muscle: 'back', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: ['Chest Supported Row', 'Supported Row'] },
  { name: 'Reverse Grip Machine Row',     muscle: 'back', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: [] },
  { name: 'Machine Shrug',                muscle: 'back', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['traps'], secondary: ['back'] },
    aliases: ['Shrug (Machine)'] },
  { name: 'Smith Machine Row',            muscle: 'back', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: [] },
  { name: 'Smith Machine Shrug',          muscle: 'back', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['traps'], secondary: ['back'] },
    aliases: [] },
  { name: 'Pull-ups',                     muscle: 'back', equipment: 'Bodyweight',    type: 'bw_reps',     muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: ['Pull Up', 'Pull-up', 'Pullup', 'Pullups'] },
  { name: 'Chin-ups',                     muscle: 'back', equipment: 'Bodyweight',    type: 'bw_reps',     muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: ['Chin Up', 'Chin-up', 'Chinup', 'Chinups'] },
  { name: 'Wide-Grip Pull-ups',           muscle: 'back', equipment: 'Bodyweight',    type: 'bw_reps',     muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: ['Wide Grip Pull Up', 'Wide Pull Up'] },
  { name: 'Neutral-Grip Pull-ups',        muscle: 'back', equipment: 'Bodyweight',    type: 'bw_reps',     muscles: { primary: ['lats', 'back'], secondary: ['biceps'] },
    aliases: ['Neutral Grip Pull Up', 'Hammer Grip Pull Up'] },
  { name: 'Inverted Row',                 muscle: 'back', equipment: 'Bodyweight',    type: 'bw_reps',     muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: ['Australian Pull Up', 'Bodyweight Row'] },
  { name: 'Back Extension',               muscle: 'back', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['lower-back', 'glutes'], secondary: ['hamstrings'] },
    aliases: ['Hyperextension', 'Back Extensions'] },
  { name: 'Landmine Row',                 muscle: 'back', equipment: 'Landmine',      type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: [] },
  { name: 'Meadows Row',                  muscle: 'back', equipment: 'Landmine',      type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: [] },
  { name: 'TRX Row',                      muscle: 'back', equipment: 'TRX',           type: 'reps_only',   muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: [] },
  { name: 'Band Pull-Apart',              muscle: 'back', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['rear-delts', 'traps'], secondary: ['back'] },
    aliases: [] },
  { name: 'Band Row',                     muscle: 'back', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: [] },
  { name: 'Kettlebell Row',               muscle: 'back', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['back', 'lats'], secondary: ['biceps', 'rear-delts'] },
    aliases: [] },
  { name: 'Kettlebell Swing',             muscle: 'back', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['glutes', 'hamstrings'], secondary: ['back', 'traps'] },
    aliases: [] },

  // ===== LEGS =====
  { name: 'Barbell Back Squat',           muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Back Squat', 'Squat', 'Barbell Squat', 'Squat (Barbell)', 'BB Squat'] },
  { name: 'Front Squat',                  muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Front Squat (Barbell)'] },
  { name: 'Zercher Squat',                muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Pause Squat',                  muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Box Squat',                    muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Romanian Deadlift',            muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: ['Romanian Deadlift (Barbell)', 'RDL', 'Stiff Leg Deadlift', 'Stiff-Legged Deadlift'] },
  { name: 'Stiff-Leg Deadlift',           muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: ['Stiff Leg Deadlift', 'SLDL'] },
  { name: 'Good Morning',                 muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: [] },
  { name: 'Barbell Lunge',                muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Lunge (Barbell)'] },
  { name: 'Barbell Hip Thrust',           muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: ['Hip Thrust (Barbell)', 'Hip Thrust'] },
  { name: 'Hip Thrust Machine',           muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: ['Hip Thrust (Machine)', 'Machine Hip Thrust', 'Glute Drive'] },
  { name: 'Barbell Calf Raise',           muscle: 'legs', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['calves'], secondary: [] },
    aliases: [] },
  { name: 'Dumbbell Squat',               muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Squat (Dumbbell)'] },
  { name: 'Goblet Squat',                 muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Dumbbell Romanian Deadlift',   muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: ['DB Romanian Deadlift', 'DB RDL', 'Romanian Deadlift (Dumbbell)'] },
  { name: 'Dumbbell Lunge',               muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Lunge (Dumbbell)', 'DB Lunge'] },
  { name: 'Walking Lunge',                muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Bulgarian Split Squat',        muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Split Squat', 'Rear Foot Elevated Split Squat', 'RFESS', 'Bulgarian Split Squat (Dumbbell)'] },
  { name: 'Dumbbell Step-up',             muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Step Up (Dumbbell)', 'Step Up'] },
  { name: 'Dumbbell Calf Raise',          muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['calves'], secondary: [] },
    aliases: ['Calf Raise (Dumbbell)'] },
  { name: 'Dumbbell Hip Thrust',          muscle: 'legs', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: [] },
  { name: 'Cable Pull-Through',           muscle: 'legs', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['glutes', 'hamstrings'], secondary: ['lower-back'] },
    aliases: [] },
  { name: 'Cable Kickback',               muscle: 'legs', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: ['Glute Kickback (Cable)'] },
  { name: 'Cable Hip Adduction',          muscle: 'legs', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: [] },
  { name: 'Cable Hip Abduction',          muscle: 'legs', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: [] },
  { name: 'Leg Press',                    muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Leg Press (Machine)', '45 Degree Leg Press'] },
  { name: 'Hack Squat',                   muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Hack Squat (Machine)'] },
  { name: 'Leg Extension',                muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['quads'], secondary: [] },
    aliases: ['Leg Extension (Machine)', 'Quad Extension', 'Knee Extension'] },
  { name: 'Seated Leg Curl',              muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: ['Leg Curl (Seated)', 'Seated Hamstring Curl'] },
  { name: 'Lying Leg Curl',               muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: ['Lying Leg Curl (Machine)', 'Leg Curl', 'Hamstring Curl', 'Leg Curl (Lying)'] },
  { name: 'Standing Leg Curl',            muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: ['Leg Curl (Standing)'] },
  { name: 'Hip Adductor Machine',         muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: ['Inner Thigh Machine', 'Adductor Machine'] },
  { name: 'Hip Abductor Machine',         muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: ['Hip Abductor (Machine)', 'Outer Thigh Machine', 'Abductor Machine'] },
  { name: 'Glute Drive Machine',          muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: [] },
  { name: 'Seated Calf Raise',            muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['calves'], secondary: [] },
    aliases: ['Seated Calf Raise (Machine)', 'Calf Raise (Seated)'] },
  { name: 'Standing Calf Raise',          muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['calves'], secondary: [] },
    aliases: ['Calf Raise (Standing)', 'Calf Raise'] },
  { name: 'Pendulum Squat',               muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Belt Squat',                   muscle: 'legs', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Smith Machine Squat',          muscle: 'legs', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Squat (Smith Machine)'] },
  { name: 'Smith Machine Romanian Deadlift', muscle: 'legs', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: ['Romanian Deadlift (Smith Machine)'] },
  { name: 'Smith Machine Lunge',          muscle: 'legs', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Lunge (Smith Machine)'] },
  { name: 'Smith Machine Hip Thrust',     muscle: 'legs', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: ['Hip Thrust (Smith Machine)'] },
  { name: 'Smith Machine Calf Raise',     muscle: 'legs', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['calves'], secondary: [] },
    aliases: [] },
  { name: 'Bodyweight Squat',             muscle: 'legs', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Air Squat'] },
  { name: 'Pistol Squat',                 muscle: 'legs', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Single Leg Squat'] },
  { name: 'Jump Squat',                   muscle: 'legs', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Bodyweight Lunge',             muscle: 'legs', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Lunge', 'Forward Lunge'] },
  { name: 'Glute Bridge',                 muscle: 'legs', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['glutes'], secondary: ['hamstrings'] },
    aliases: ['Bodyweight Hip Thrust', 'Floor Hip Thrust'] },
  { name: 'Nordic Hamstring Curl',        muscle: 'legs', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: ['Nordic Curl'] },
  { name: 'Wall Sit',                     muscle: 'legs', equipment: 'Bodyweight',    type: 'time_only',   muscles: { primary: ['quads'], secondary: ['glutes'] },
    aliases: [] },
  { name: 'Kettlebell Goblet Squat',      muscle: 'legs', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: ['Goblet Squat (Kettlebell)'] },
  { name: 'Kettlebell Deadlift',          muscle: 'legs', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Kettlebell Lunge',             muscle: 'legs', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Band Squat',                   muscle: 'legs', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Band Leg Curl',                muscle: 'legs', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: [] },
  { name: 'Landmine Squat',               muscle: 'legs', equipment: 'Landmine',      type: 'weight_reps', muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
    aliases: [] },
  { name: 'Landmine Romanian Deadlift',   muscle: 'legs', equipment: 'Landmine',      type: 'weight_reps', muscles: { primary: ['hamstrings'], secondary: ['glutes'] },
    aliases: [] },

  // ===== SHOULDERS =====
  { name: 'Barbell Overhead Press',       muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: ['OHP', 'Overhead Press', 'Military Press', 'Overhead Press (Barbell)', 'Standing Press'] },
  { name: 'Push Press',                   muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: [] },
  { name: 'Behind-the-Neck Press',        muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: ['Behind the Neck Press'] },
  { name: 'Barbell Upright Row',          muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['side-delts', 'traps'], secondary: ['front-delts'] },
    aliases: ['Upright Row (Barbell)', 'Upright Row'] },
  { name: 'Barbell Front Raise',          muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['front-delts'], secondary: ['side-delts'] },
    aliases: [] },
  { name: 'Bradford Press',               muscle: 'shoulders', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: [] },
  { name: 'Dumbbell Shoulder Press',      muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: ['Seated Overhead Press (Dumbbell)', 'Seated Dumbbell Press', 'DB Shoulder Press', 'Dumbbell OHP', 'Overhead Press (Dumbbell)', 'DB Press'] },
  { name: 'Arnold Press',                 muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps'] },
    aliases: [] },
  { name: 'Lateral Raise',                muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] },
    aliases: ['Lateral Raise (Dumbbell)', 'Side Raise', 'Side Lateral Raise', 'DB Lateral Raise', 'Dumbbell Lateral Raise'] },
  { name: 'Front Raise',                  muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['front-delts'], secondary: ['side-delts'] },
    aliases: ['Front Raise (Dumbbell)', 'DB Front Raise', 'Dumbbell Front Raise'] },
  { name: 'Dumbbell Upright Row',         muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['side-delts', 'traps'], secondary: ['front-delts'] },
    aliases: ['Upright Row (Dumbbell)'] },
  { name: 'Reverse Flye',                 muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] },
    aliases: ['Reverse Fly', 'Bent Over Lateral Raise', 'Rear Delt Fly (Dumbbell)'] },
  { name: 'Dumbbell Shrug (Shoulders)',   muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['traps'], secondary: [] },
    aliases: [] },
  { name: 'Lu Raise',                     muscle: 'shoulders', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] },
    aliases: [] },
  { name: 'Cable Lateral Raise',          muscle: 'shoulders', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] },
    aliases: ['Cable Side Raise', 'Low Cable Lateral Raise'] },
  { name: 'Cable Front Raise',            muscle: 'shoulders', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['front-delts'], secondary: ['side-delts'] },
    aliases: [] },
  { name: 'Cable Reverse Flye',           muscle: 'shoulders', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] },
    aliases: ['Cable Reverse Fly', 'Rear Delt Fly (Cable)'] },
  { name: 'Cable Upright Row',            muscle: 'shoulders', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['side-delts', 'traps'], secondary: ['front-delts'] },
    aliases: [] },
  { name: 'Cable Face Pull',              muscle: 'shoulders', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] },
    aliases: [] },
  { name: 'Cable Shoulder Press',         muscle: 'shoulders', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: [] },
  { name: 'Machine Shoulder Press',       muscle: 'shoulders', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: ['Shoulder Press (Machine)', 'Overhead Press (Machine)'] },
  { name: 'Machine Lateral Raise',        muscle: 'shoulders', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] },
    aliases: ['Lateral Raise (Machine)'] },
  { name: 'Reverse Pec Deck',             muscle: 'shoulders', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] },
    aliases: ['Rear Delt Fly Machine', 'Rear Delt Fly (Machine)', 'Rear delt fly machine', 'Reverse Fly Machine', 'Pec Deck Reverse'] },
  { name: 'Smith Machine Overhead Press', muscle: 'shoulders', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: ['Overhead Press (Smith Machine)'] },
  { name: 'Smith Machine Behind-Neck Press', muscle: 'shoulders', equipment: 'Smith Machine', type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: [] },
  { name: 'Handstand Push-up',            muscle: 'shoulders', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: ['HSPU'] },
  { name: 'Pike Push-up',                 muscle: 'shoulders', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: ['Pike Pushup', 'Pike Push Up'] },
  { name: 'Kettlebell Press',             muscle: 'shoulders', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: ['KB Press', 'Kettlebell Overhead Press'] },
  { name: 'Kettlebell Lateral Raise',     muscle: 'shoulders', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] },
    aliases: [] },
  { name: 'Kettlebell Upright Row',       muscle: 'shoulders', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['side-delts', 'traps'], secondary: ['front-delts'] },
    aliases: [] },
  { name: 'Band Lateral Raise',           muscle: 'shoulders', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] },
    aliases: [] },
  { name: 'Band Face Pull',               muscle: 'shoulders', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] },
    aliases: [] },
  { name: 'Band Pull-Apart (Shoulders)',  muscle: 'shoulders', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['rear-delts'], secondary: ['traps'] },
    aliases: [] },
  { name: 'Landmine Press (Shoulders)',   muscle: 'shoulders', equipment: 'Landmine',      type: 'weight_reps', muscles: { primary: ['front-delts', 'side-delts'], secondary: ['triceps', 'traps'] },
    aliases: [] },
  { name: 'Landmine Lateral Raise',       muscle: 'shoulders', equipment: 'Landmine',      type: 'weight_reps', muscles: { primary: ['side-delts'], secondary: [] },
    aliases: [] },

  // ===== ARMS =====
  { name: 'Barbell Curl',                 muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: ['Bicep Curl (Barbell)', 'BB Curl'] },
  { name: 'EZ-Bar Curl',                  muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: ['EZ Bar Curl', 'EZ Curl'] },
  { name: 'Preacher Curl (Barbell)',      muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: ['Preacher Curl'] },
  { name: 'Reverse Barbell Curl',         muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: ['Reverse Curl'] },
  { name: 'Drag Curl',                    muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Dumbbell Curl',                muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: ['Bicep Curl (Dumbbell)', 'DB Curl', 'Alternating Dumbbell Curl'] },
  { name: 'Hammer Curl',                  muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: ['Hammer Curl (Dumbbell)', 'DB Hammer Curl', 'Neutral Grip Curl'] },
  { name: 'Incline Dumbbell Curl',        muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: ['Bicep Curl Incline', 'Incline Curl', 'Incline Bicep Curl'] },
  { name: 'Concentration Curl',           muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Preacher Curl (Dumbbell)',     muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Zottman Curl',                 muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Cross-Body Curl',              muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Cable Curl',                   muscle: 'arms', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: ['Bicep Curl (Cable)', 'Cable Bicep Curl', 'Low Pulley Curl'] },
  { name: 'Cable Rope Curl',              muscle: 'arms', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: ['Bicep Curl Rope (Cable)', 'Rope Curl', 'Cable Hammer Curl (Rope)'] },
  { name: 'Cable Hammer Curl',            muscle: 'arms', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: ['Hammer Curl (Cable)'] },
  { name: 'Overhead Cable Curl',          muscle: 'arms', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Machine Preacher Curl',        muscle: 'arms', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms', 'lats'] },
    aliases: ['Preacher Curl (Machine)'] },
  { name: 'Machine Curl',                 muscle: 'arms', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms', 'lats'] },
    aliases: ['Bicep Curl (Machine)'] },
  { name: 'Kettlebell Curl',              muscle: 'arms', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Band Curl',                    muscle: 'arms', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Skull Crushers',               muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['Skull Crusher', 'Lying Tricep Extension', 'French Press'] },
  { name: 'EZ-Bar Skull Crushers',        muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['EZ Bar Skull Crushers', 'EZ Skull Crushers'] },
  { name: 'Close-Grip Bench Press (Triceps)', muscle: 'arms', equipment: 'Barbell',  type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'JM Press',                     muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Dumbbell Tricep Extension',    muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['DB Tricep Extension', 'Tricep Extension (Dumbbell)'] },
  { name: 'Overhead Dumbbell Extension',  muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['Overhead Tricep Extension (Dumbbell)', 'DB Overhead Extension'] },
  { name: 'Dumbbell Kickback',            muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['Tricep Kickback (Dumbbell)', 'Tricep Kickback'] },
  { name: 'Tate Press',                   muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Tricep Pushdown',              muscle: 'arms', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['Triceps Pushdown (Cable - Straight Bar)', 'Triceps Pushdown', 'Cable Pushdown', 'Cable Tricep Pushdown', 'Pushdown'] },
  { name: 'Overhead Cable Extension',     muscle: 'arms', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['Triceps Extension (Cable)', 'Cable Overhead Extension', 'Overhead Tricep Extension (Cable)'] },
  { name: 'Reverse Grip Pushdown',        muscle: 'arms', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['Reverse Pushdown'] },
  { name: 'Single Arm Pushdown',          muscle: 'arms', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['One Arm Pushdown'] },
  { name: 'Cable Kickback',               muscle: 'arms', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['Tricep Kickback (Cable)'] },
  { name: 'Tricep Dip Machine',           muscle: 'arms', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Wrist Curl',                   muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['forearms'], secondary: [] },
    aliases: [] },
  { name: 'Reverse Wrist Curl',           muscle: 'arms', equipment: 'Barbell',       type: 'weight_reps', muscles: { primary: ['forearms'], secondary: [] },
    aliases: [] },
  { name: 'Dumbbell Wrist Curl',          muscle: 'arms', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['forearms'], secondary: [] },
    aliases: [] },
  { name: "Farmer's Walk",                muscle: 'arms', equipment: 'Dumbbell',      type: 'distance_time', muscles: { primary: ['forearms'], secondary: [] },
    aliases: ["Farmer's Carry", 'Farmers Walk'] },
  { name: 'Dips',                         muscle: 'arms', equipment: 'Bodyweight',    type: 'bw_reps',     muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['Triceps Dip', 'Tricep Dip', 'Parallel Bar Dip'] },
  { name: 'Assisted Dips',                muscle: 'arms', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['chest', 'front-delts'] },
    aliases: ['Triceps Dip (Assisted)', 'Tricep Dip (Assisted)', 'Assisted Tricep Dip'] },
  { name: 'Bench Dips',                   muscle: 'arms', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: ['Tricep Bench Dip'] },
  { name: 'Diamond Push-ups (Triceps)',   muscle: 'arms', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Chin-ups (Arms focus)',        muscle: 'arms', equipment: 'Bodyweight',    type: 'bw_reps',     muscles: { primary: ['biceps'], secondary: ['forearms', 'lats'] },
    aliases: [] },
  { name: 'Band Pushdown',                muscle: 'arms', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Band Curl (Arms)',             muscle: 'arms', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['biceps'], secondary: ['forearms'] },
    aliases: [] },
  { name: 'Kettlebell Tricep Extension',  muscle: 'arms', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['triceps'], secondary: ['forearms'] },
    aliases: [] },

  // ===== CORE =====
  { name: 'Plank',                        muscle: 'core', equipment: 'Bodyweight',    type: 'time_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Side Plank',                   muscle: 'core', equipment: 'Bodyweight',    type: 'time_only',   muscles: { primary: ['obliques'], secondary: ['abs'] }, aliases: [] },
  { name: 'Dead Bug',                     muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Bird Dog',                     muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Crunch',                       muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] },
    aliases: ['Basic Crunch', 'Abdominal Crunch'] },
  { name: 'Machine Crunch',               muscle: 'core', equipment: 'Machine',       type: 'weight_reps', muscles: { primary: ['abs'], secondary: ['obliques'] },
    aliases: ['Ab Machine Crunch', 'Crunch (Machine)', 'Crunch Machine'] },
  { name: 'Bicycle Crunch',               muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Reverse Crunch',               muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Decline Crunch',               muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] },
    aliases: ['Decline Sit-up', 'Decline Crunch (Bodyweight)'] },
  { name: 'Sit-up',                       muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] },
    aliases: ['Situp', 'Jackknife Sit Up', 'Jackknife Sit-Up'] },
  { name: 'V-up',                         muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Toe Touch',                    muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Mountain Climber',             muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Hanging Leg Raise',            muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] },
    aliases: ['Hanging Knee Raise', 'Hanging Leg Raise (Bar)'] },
  { name: 'Lying Leg Raise',              muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] },
    aliases: ['Flat Leg Raise', 'Leg Raise', 'Lying Leg Raises'] },
  { name: 'Flutter Kicks',                muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Scissor Kicks',                muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Ab Wheel Rollout',             muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: ['Ab Rollout'] },
  { name: 'Dragon Flag',                  muscle: 'core', equipment: 'Bodyweight',    type: 'reps_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'L-Sit',                        muscle: 'core', equipment: 'Bodyweight',    type: 'time_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Hollow Body Hold',             muscle: 'core', equipment: 'Bodyweight',    type: 'time_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Cable Woodchop',               muscle: 'core', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['obliques'], secondary: ['abs'] }, aliases: [] },
  { name: 'Cable Crunch',                 muscle: 'core', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Pallof Press',                 muscle: 'core', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['obliques', 'abs'], secondary: [] }, aliases: [] },
  { name: 'Cable Rotation',               muscle: 'core', equipment: 'Cable',         type: 'weight_reps', muscles: { primary: ['obliques'], secondary: ['abs'] }, aliases: [] },
  { name: 'Russian Twist',                muscle: 'core', equipment: 'Dumbbell',      type: 'weight_reps', muscles: { primary: ['obliques'], secondary: ['abs'] }, aliases: [] },
  { name: 'Weighted Plank',               muscle: 'core', equipment: 'Barbell',       type: 'time_only',   muscles: { primary: ['abs'], secondary: ['obliques'] }, aliases: [] },
  { name: 'Kettlebell Windmill',          muscle: 'core', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['obliques'], secondary: ['abs'] }, aliases: [] },
  { name: 'Turkish Get-up',               muscle: 'core', equipment: 'Kettlebell',    type: 'weight_reps', muscles: { primary: ['abs', 'obliques'], secondary: ['front-delts', 'glutes'] }, aliases: [] },
  { name: 'Band Anti-Rotation',           muscle: 'core', equipment: 'Band',          type: 'weight_reps', muscles: { primary: ['obliques'], secondary: ['abs'] }, aliases: [] },

  // ===== CARDIO =====
  { name: 'Treadmill Running',            muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Running (Treadmill)'] },
  { name: 'Treadmill Walking',            muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Walking (Treadmill)'] },
  { name: 'Treadmill Incline Walk',       muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Incline Walk'] },
  { name: 'Stationary Bike',              muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Bike', 'Exercise Bike'] },
  { name: 'Spin Bike',                    muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Indoor Cycling'] },
  { name: 'Recumbent Bike',               muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Assault Bike',                 muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Air Bike', 'Fan Bike'] },
  { name: 'Rowing Machine',               muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Erg', 'Concept 2', 'Rowing Erg'] },
  { name: 'Elliptical',                   muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Cross Trainer'] },
  { name: 'Stair Climber',                muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['StairMaster', 'Stairmaster'] },
  { name: 'Ski Erg',                      muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: "Jacob's Ladder",               muscle: 'cardio', equipment: 'Machine',     type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Outdoor Running',              muscle: 'cardio', equipment: 'Bodyweight',  type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Running', 'Jogging'] },
  { name: 'Outdoor Walking',              muscle: 'cardio', equipment: 'Bodyweight',  type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Walking'] },
  { name: 'Outdoor Cycling',              muscle: 'cardio', equipment: 'Bodyweight',  type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: ['Cycling', 'Biking'] },
  { name: 'Swimming',                     muscle: 'cardio', equipment: 'Bodyweight',  type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Hiking',                       muscle: 'cardio', equipment: 'Bodyweight',  type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Jump Rope',                    muscle: 'cardio', equipment: 'Bodyweight',  type: 'time_only',     muscles: { primary: [], secondary: [] }, aliases: ['Skipping', 'Skipping Rope'] },
  { name: 'Jumping Jacks',                muscle: 'cardio', equipment: 'Bodyweight',  type: 'time_only',     muscles: { primary: [], secondary: [] }, aliases: ['Star Jumps'] },
  { name: 'Burpees',                      muscle: 'cardio', equipment: 'Bodyweight',  type: 'reps_only',     muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Box Jump',                     muscle: 'cardio', equipment: 'Bodyweight',  type: 'reps_only',     muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Battle Ropes',                 muscle: 'cardio', equipment: 'Other',       type: 'time_only',     muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Sled Push',                    muscle: 'cardio', equipment: 'Other',       type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Sled Pull',                    muscle: 'cardio', equipment: 'Other',       type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Tire Flip',                    muscle: 'cardio', equipment: 'Other',       type: 'reps_only',     muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Kettlebell Swing (Cardio)',    muscle: 'cardio', equipment: 'Kettlebell',  type: 'weight_reps',   muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Kettlebell Snatch',            muscle: 'cardio', equipment: 'Kettlebell',  type: 'weight_reps',   muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Kettlebell Clean & Press',     muscle: 'cardio', equipment: 'Kettlebell',  type: 'weight_reps',   muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Barbell Thruster',             muscle: 'cardio', equipment: 'Barbell',     type: 'weight_reps',   muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Dumbbell Thruster',            muscle: 'cardio', equipment: 'Dumbbell',    type: 'weight_reps',   muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Man Maker',                    muscle: 'cardio', equipment: 'Dumbbell',    type: 'weight_reps',   muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Devil Press',                  muscle: 'cardio', equipment: 'Dumbbell',    type: 'weight_reps',   muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Bear Crawl',                   muscle: 'cardio', equipment: 'Bodyweight',  type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Sprints',                      muscle: 'cardio', equipment: 'Bodyweight',  type: 'distance_time', muscles: { primary: [], secondary: [] }, aliases: [] },

  // ===== MOBILITY =====
  { name: 'Foam Roll - Upper Back',       muscle: 'mobility', equipment: 'Other',     type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Foam Roll - Quads',            muscle: 'mobility', equipment: 'Other',     type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Foam Roll - Hamstrings',       muscle: 'mobility', equipment: 'Other',     type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Foam Roll - IT Band',          muscle: 'mobility', equipment: 'Other',     type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Foam Roll - Lats',             muscle: 'mobility', equipment: 'Other',     type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Foam Roll - Calves',           muscle: 'mobility', equipment: 'Other',     type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Hip Flexor Stretch',           muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Pigeon Stretch',               muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: '90/90 Hip Stretch',            muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Couch Stretch',                muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: "World's Greatest Stretch",    muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Cat-Cow',                      muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Thoracic Spine Rotation',      muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Shoulder Dislocates',          muscle: 'mobility', equipment: 'Band',      type: 'reps_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Band Pull-Apart (Warmup)',     muscle: 'mobility', equipment: 'Band',      type: 'reps_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Wall Slide',                   muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Scapular Push-up',             muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Face-the-Wall Squat',          muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Ankle Dorsiflexion Stretch',   muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Hamstring Stretch',            muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Quad Stretch',                 muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Calf Stretch',                 muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Chest Stretch (Doorway)',      muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Lat Stretch',                  muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Tricep Stretch',               muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Neck Stretch',                 muscle: 'mobility', equipment: 'Bodyweight', type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Wrist Circles',                muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Leg Swings',                   muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'Arm Circles',                  muscle: 'mobility', equipment: 'Bodyweight', type: 'reps_only', muscles: { primary: [], secondary: [] }, aliases: [] },
  { name: 'TRX Squat Stretch',            muscle: 'mobility', equipment: 'TRX',       type: 'time_only', muscles: { primary: [], secondary: [] }, aliases: [] },
]

// Exercise type labels
export const TYPE_LABELS = {
  weight_reps: 'Weight + Reps',
  bw_reps: 'BW ± kg',
  reps_only: 'Reps only',
  time_only: 'Time',
  distance_time: 'Distance + Time',
}

// Filter exercises by criteria — now also searches aliases
export function filterExercises(allExercises, { search = '', muscles = [], equipment = 'all', myOnly = false }) {
  return allExercises.filter(ex => {
    if (myOnly && !ex.isCustom) return false
    if (muscles.length > 0 && !muscles.includes(ex.muscle)) return false
    if (equipment !== 'all' && ex.equipment !== equipment) return false
    if (search) {
      const q = search.toLowerCase()
      const matchesName = ex.name.toLowerCase().includes(q)
      const matchesAlias = (ex.aliases || []).some(a => a.toLowerCase().includes(q))
      if (!matchesName && !matchesAlias) return false
    }
    return true
  })
}

// Group exercises by muscle
export function groupByMuscle(exercises) {
  const groups = {}
  const order = ['chest', 'back', 'legs', 'shoulders', 'arms', 'core', 'cardio', 'mobility']
  for (const m of order) groups[m] = []
  for (const ex of exercises) {
    if (!groups[ex.muscle]) groups[ex.muscle] = []
    groups[ex.muscle].push(ex)
  }
  return Object.entries(groups).filter(([, exs]) => exs.length > 0)
}
